version: '3.8'

services:
  frontend:
    build:
      context: ./admin-web
      dockerfile: Dockerfile
    ports:
      - "8008:80"
    volumes:
      - ./admin-web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always

networks:
  default:
    driver: bridge 