version: '3.8'

services:
  app:
    container_name: chinese-culture
    image: 1047028213/chinese-culture:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:80"
    environment:
      - NODE_ENV=production
    restart: always